[package]
name = "music-bio"
version = "0.1.0"
authors = ["Ving <viing937@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
actix-web = { version = "3", features = ["openssl"] }
dotenv = "0.15.0"
url = "2.2.0"
openssl = "0.10.32"
serde = "1.0.118"
serde_json = "1.0.61"
hex = "0.4.2"
